#!/usr/bin/env bash
set -euo pipefail

USAGE="Usage: $0 [--mode local|gcp|lambda] [--gpu t4|a100|a100-2g|a100-4g|a100-8g] [--no-idempotent] [--force-modulate] [--label LABEL]"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LANG_DIR="$SCRIPT_DIR/../../modulators/language"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
CLI_TOKEN_FILE="$SCRIPT_DIR/.cli_token"
SESSION_FILE="${HOME}/.ephapsys_state/session.json"

MODE="local"
GPU="t4"
IDEMPOTENT=1
FORCE_MODULATE=0
FORCE_REGISTER=0
SKIP_BUILD_FLAG=""
SKIP_PUSH_FLAG=""
LABEL=""
BOLD="\033[1m"
DIM="\033[2m"
BLUE="\033[36m"
GREEN="\033[32m"
YELLOW="\033[33m"
MAGENTA="\033[35m"
WHITE="\033[97m"
GOLD="\033[38;5;220m"
RESET="\033[0m"

info() {
  printf "${BLUE}[INFO]${RESET} %b\n" "$*"
}

warn() {
  printf "${YELLOW}[WARN]${RESET} %b\n" "$*" >&2
}

error() {
  printf "${MAGENTA}[ERROR]${RESET} %b\n" "$*" >&2
}

require_cmd() {
  local cmd="$1"
  command -v "$cmd" >/dev/null 2>&1 || {
    error "Missing required command: $cmd"
    exit 1
  }
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="$2"
      shift 2
      ;;
    --local)
      MODE="local"
      shift
      ;;
    --gcp)
      MODE="gcp"
      shift
      ;;
    --lambda)
      MODE="lambda"
      shift
      ;;
    --gpu)
      # --gpu only matters for GCP (Lambda picks via LAMBDA_INSTANCE_TYPES env);
      # historically this also implicitly switched MODE to gcp. Preserve that
      # behavior for the GCP case but don't override an explicit --lambda.
      if [ "$MODE" != "lambda" ]; then
        MODE="gcp"
      fi
      GPU="$2"
      shift 2
      ;;
    --idempotent)
      IDEMPOTENT=1
      shift
      ;;
    --no-idempotent)
      IDEMPOTENT=0
      shift
      ;;
    --force-modulate)
      FORCE_MODULATE=1
      shift
      ;;
    --force-register)
      FORCE_REGISTER=1
      shift
      ;;
    --no-build)
      SKIP_BUILD_FLAG="--no-build"
      shift
      ;;
    --no-push)
      SKIP_PUSH_FLAG="--no-push"
      shift
      ;;
    --label)
      LABEL="$2"
      shift 2
      ;;
    -h|--help)
      echo "$USAGE"
      exit 0
      ;;
    *)
      error "Unknown argument: $1"
      echo "$USAGE"
      exit 1
      ;;
  esac
done

case "$MODE" in
  local|gcp|lambda) ;;
  *)
    error "--mode must be one of: local, gcp, lambda"
    exit 1
    ;;
esac

require_cmd curl
require_cmd jq
require_cmd python3

if [[ ! -f "$ENV_FILE" && -f "$ENV_EXAMPLE" ]]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  info "Created $ENV_FILE from .env.example. Fill in AOC_ORG_ID, AOC_PROVISIONING_TOKEN, and AOC_MODULATION_TOKEN, then rerun."
  exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
  error "Missing $ENV_FILE"
  exit 1
fi

set -a
source "$ENV_FILE"
# Provider-specific env (LAMBDA_API_KEY, LAMBDA_SSH_*, etc.) lives in
# .env.lambda — same pattern as GCP utility scripts use .env.gcp. Sourced
# only when --mode lambda is selected so users running --mode local|gcp
# aren't required to set up Lambda creds.
if [[ "$MODE" == "lambda" && -f "$SCRIPT_DIR/.env.lambda" ]]; then
  source "$SCRIPT_DIR/.env.lambda"
fi
set +a

AOC_API="${AOC_BASE_URL:-${AOC_API_URL:-${AOC_API_BASE:-${AOC_API:-http://localhost:7001}}}}"
CLI_API="${AOC_API}/cli"
ORG_ID="${AOC_ORG_ID:-}"
API_TOKEN="${API_TOKEN:-${AOC_MODULATION_TOKEN:-}}"
HF_TOKEN="${HF_TOKEN:-}"
MODEL_REPO="${HELLOWORLD_MODEL_REPO:-Qwen/Qwen3.5-0.8B}"
MODEL_REVISION="${HELLOWORLD_MODEL_REVISION:-main}"
MODEL_KIND="${HELLOWORLD_MODEL_KIND:-language}"
MODEL_NAME="${HELLOWORLD_MODEL_NAME:-HelloWorld Starter Model}"
AGENT_LABEL="${LABEL:-${AGENT_TEMPLATE_NAME:-HelloWorld Agent Template}}"
AGENT_DESCRIPTION="${HELLOWORLD_AGENT_DESCRIPTION:-Starter HelloWorld agent template generated by push.sh}"
DEFAULT_POLICY_JSON='[{"type":"output_moderation","value":{"categories":["self-harm","violence"],"action":"block"},"status":"active"},{"type":"prompt_injection_defense","value":{"action":"block"},"status":"active"}]'

model_size_label() {
  case "$MODEL_REPO" in
    Qwen/Qwen3.5-0.8B) printf '0.8B params';;
    google/flan-t5-small) printf '~80M params';;
    *) printf 'size not annotated';;
  esac
}

print_plan() {
  local publish_mode="full modulation"
  local plan_label="${MODEL_NAME:-Starter Model}"
  if [[ "$IDEMPOTENT" -eq 1 ]]; then
    publish_mode="idempotent (skip modulation)"
  fi
  printf "\n${GOLD}%s${RESET}\n" "$plan_label"
  printf "  Model repo:       %s\n" "$MODEL_REPO"
  printf "  Model size:       %s\n" "$(model_size_label)"
  printf "  Publish mode:     %s\n" "$publish_mode"
  printf "  Agent template:   %s\n\n" "$AGENT_LABEL"
}

step() {
  printf "${GOLD}[STEP]${RESET} %s\n" "$*"
}

progress() {
  if [[ -t 1 ]]; then
    printf "\r\033[2K${GOLD}[WAIT]${RESET} %s" "$*"
  else
    printf "${GOLD}[WAIT]${RESET} %s\n" "$*"
  fi
}

progress_done() {
  if [[ -t 1 ]]; then
    printf "\r\033[2K"
  fi
}

if [[ -z "$ORG_ID" ]]; then
  error "AOC_ORG_ID must be set in $ENV_FILE"
  exit 1
fi

if [[ -z "$API_TOKEN" ]]; then
  error "AOC_MODULATION_TOKEN (or API_TOKEN) must be set in $ENV_FILE"
  exit 1
fi

AUTH_HEADER=(-H "Authorization: Bearer ${API_TOKEN}")

save_env_var() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" "$ENV_FILE"; then
    sed -i '' "s|^${key}=.*|${key}=${value}|" "$ENV_FILE" 2>/dev/null || sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '\n%s=%s\n' "$key" "$value" >>"$ENV_FILE"
  fi
}

cli_login() {
  local token=""
  local session_base_url=""
  if [[ -f "$SESSION_FILE" ]]; then
    token=$(jq -r '.token // empty' "$SESSION_FILE" 2>/dev/null || true)
    session_base_url=$(jq -r '.base_url // empty' "$SESSION_FILE" 2>/dev/null || true)
    if [[ -n "$token" ]]; then
      local code
      code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $token" "$CLI_API/models/list")
      if [[ "$code" == "200" ]]; then
        info "Reusing CLI session from ~/.ephapsys_state/session.json" >&2
        printf '%s' "$token"
        return
      fi
      if [[ -n "$session_base_url" && "$session_base_url" != "$AOC_API" ]]; then
        warn "Saved CLI session targets $session_base_url but push.sh is targeting $AOC_API" >&2
      fi
    fi
  fi
  if [[ -f "$CLI_TOKEN_FILE" ]]; then
    token=$(cat "$CLI_TOKEN_FILE")
    local code
    code=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer $token" "$CLI_API/models/list")
    if [[ "$code" == "200" ]]; then
      info "Reusing cached CLI token from .cli_token" >&2
      printf '%s' "$token"
      return
    fi
  fi

  if [[ ! -t 0 ]]; then
    error "No valid CLI session found for model registration. Run 'ephapsys login' first, then rerun push.sh."
    exit 1
  fi

  warn "No reusable CLI session found for ${AOC_API}; falling back to interactive CLI login." >&2

  local cli_user cli_pass login_resp
  printf "  ${WHITE}${BOLD}Enter your Ephapsys account email:${RESET} " >&2
  read -r cli_user
  printf "  ${WHITE}${BOLD}Enter your Ephapsys account password:${RESET} " >&2
  read -r -s cli_pass
  printf "\n\n" >&2
  login_resp=$(curl -sS -X POST "$CLI_API/login" \
    -H "Content-Type: application/json" \
    -d "{\"username\":\"${cli_user}\",\"password\":\"${cli_pass}\"}")
  token=$(echo "$login_resp" | jq -r '.token // empty')
  if [[ -z "$token" ]]; then
    error "CLI login failed"
    echo "$login_resp" >&2
    exit 1
  fi
  printf '%s' "$token" >"$CLI_TOKEN_FILE"
  mkdir -p "$(dirname "$SESSION_FILE")"
  jq -n --arg token "$token" --arg base_url "$AOC_API" --argjson raw "$login_resp" '
    ($raw | if type == "object" then . else {} end) + {token: $token, base_url: $base_url}
  ' >"$SESSION_FILE"
  printf '%s' "$token"
}

fetch_model_templates() {
  curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models?type=TEMPLATE"
}

resolve_model_template() {
  # Filter to REGISTERED only — skip DOWNLOAD_FAILED / DOWNLOADING so we
  # reuse a known-good template when a recent registration broke. Without
  # this, resolve returns the latest-matching template regardless of
  # status and push.sh hands a broken ID to wait_for_model_download.
  # Old behavior preserved as comment in case healthy filter ever needs
  # to be relaxed:
  #   | map(select(... model_kind match AND repo|name match))
  fetch_model_templates | jq -r --arg repo "$MODEL_REPO" --arg kind "$MODEL_KIND" --arg name "$MODEL_NAME" '
    (.items // [])
    | map(select((((.model_kind // .kind // "") | ascii_downcase) == ($kind | ascii_downcase))
      and ((.source_repo // "") == $repo or (.name // "") == $name or (.name // "") == ("HuggingFace " + $repo))
      and (((.status // "") | ascii_upcase) == "REGISTERED")))
    | sort_by(.created_at // 0)
    | last
    | (.ID // .public_id // .internal_id // ._id // empty)'
}

register_model_template() {
  local cli_token="$1"
  local payload
  local response
  local ok
  cli_token="$(printf '%s' "$cli_token" | tr -d '\r\n')"
  step "Registering model template in AOC for ${MODEL_REPO}"
  payload=$(jq -n \
    --arg provider "huggingface" \
    --arg model_repo "$MODEL_REPO" \
    --arg revision "$MODEL_REVISION" \
    --arg model_name "$MODEL_NAME" \
    --arg model_kind "$MODEL_KIND" \
    --arg hf_token "$HF_TOKEN" \
    '{
      provider: $provider,
      ids: [$model_repo],
      repo_id: $model_repo,
      revision: $revision,
      auto_register: true,
      name: $model_name,
      model_kind: $model_kind
    } + (if ($hf_token | gsub("^\\s+|\\s+$"; "")) != "" then {hf_token: $hf_token} else {} end)')
  response=$(curl -sS -X POST "$CLI_API/models/register" \
    -H "Authorization: Bearer ${cli_token}" \
    -H "Content-Type: application/json" \
    -d "$payload")
  ok=$(printf '%s' "$response" | jq -r '.ok // empty' 2>/dev/null || true)
  if [[ "$ok" != "true" ]]; then
    error "Model registration failed"
    printf '%s\n' "$response" >&2
    exit 1
  fi
  info "Model registration request accepted by AOC."
}

wait_for_model_download() {
  local model_id="$1"
  local max_attempts="${2:-120}"
  local delay="${3:-5}"
  local status elapsed tick
  local spin=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
  local start_ts=$SECONDS
  for ((i=1; i<=max_attempts; i++)); do
    status=$(curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models/${model_id}" | jq -r '.status // empty' 2>/dev/null || true)
    case "$status" in
      DOWNLOADING)
        # Gradient bouncing bar during the poll delay
        local bar_w=40
        local -a gc=('\033[38;5;27m' '\033[38;5;33m' '\033[38;5;39m' '\033[38;5;45m' '\033[38;5;48m' '\033[38;5;42m' '\033[38;5;46m' '\033[38;5;118m' '\033[38;5;190m' '\033[38;5;220m')
        for ((tick=0; tick<delay*5; tick++)); do
          elapsed=$((SECONDS - start_ts))
          if [[ -t 1 ]]; then
            local pos=$(( tick % (bar_w * 2) ))
            if (( pos >= bar_w )); then pos=$(( bar_w * 2 - pos )); fi
            local bar=""
            for ((b=0; b<bar_w; b++)); do
              if (( b >= pos && b < pos + 6 )); then
                local ci=$(( (b - pos) * 9 / 5 ))
                bar+="${gc[$ci]}█"
              else
                bar+="\033[2m░"
              fi
            done
            printf "\r  ${bar}${RESET}  Securing model in AOC ${DIM}(%ds)${RESET}    " "$elapsed"
          fi
          sleep 0.2
        done
        ;;
      DOWNLOAD_FAILED)
        [[ -t 1 ]] && printf "\r\033[2K"
        error "Model download failed on the server"
        exit 1
        ;;
      *)
        elapsed=$((i * delay))
        [[ -t 1 ]] && printf "\r\033[2K"
        printf "  ${GREEN}+${RESET} Model secured in AOC ${DIM}(%ds)${RESET}\n" "$elapsed"
        return 0
        ;;
    esac
  done
  [[ -t 1 ]] && printf "\r\033[2K"
  error "Model download timed out after $((max_attempts * delay))s"
  exit 1
}

model_ready() {
  local model_id="$1"
  curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models/${model_id}" | jq -e '
    (
      (.Modulated // false) == true
      or (.Modulation.status // "") == "completed"
      or (
        (.Modulation.status // "") == "idempotent"
        and ((.Modulation.finished_at // 0) > 0)
      )
    )
    and (
      (((.artifact_urls // {}) | length) > 0)
      or ((.artifact_url // "") != "")
      or ((.storage_path // "") != "")
      or ((((.Modulation.artifact_urls // {}) | length)) > 0)
      or ((.Modulation.ecm_digest // "") != "")
    )' >/dev/null
}

poll_until_ready() {
  local model_id="$1"
  local timeout="${2:-7200}"
  local interval="${3:-5}"
  local deadline=$(( $(date +%s) + timeout ))
  local started=$(( $(date +%s) ))
  local -a spinner=('|' '/' '-' '\\')
  local spin_idx=0
  step "Waiting for model template ${model_id} to become ready"
  # Bound consecutive malformed-response failures so a broken backend
  # doesn't cause an infinite spin. See ephapsys-research#7. Without this
  # cap, a 502/504/HTML-error-page response from the API caused a 2.5+ min
  # silent hang on 2026-05-01 with the operator unable to tell what went
  # wrong from the repeated "jq: parse error" lines.
  local parse_failures=0
  local last_raw_response=""
  local MAX_PARSE_FAILURES=10
  while true; do
    if model_ready "$model_id"; then
      local elapsed=$(( $(date +%s) - started ))
      progress_done
      printf "${GREEN}[DONE]${RESET} Model template %s is ready after %ss.\n" "$model_id" "$elapsed"
      return 0
    fi
    if (( $(date +%s) >= deadline )); then
      progress_done
      error "Timed out waiting for model template ${model_id} to become ready"
      return 1
    fi
    local raw_response
    raw_response="$(curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/models/${model_id}" 2>/dev/null || true)"
    last_raw_response="$raw_response"
    local status_line
    if echo "$raw_response" | jq -e . >/dev/null 2>&1; then
      # Valid JSON — reset failure counter and extract status fields
      parse_failures=0
      status_line="$(echo "$raw_response" | jq -r '
        [
          ("status=" + ((.Modulation.status // .status // "unknown") | tostring)),
          ("modulated=" + (((.Modulated // false) | tostring))),
          ("artifacts=" + (((((.artifact_urls // {}) | length) + ((.Modulation.artifact_urls // {}) | length))) | tostring))
        ] | join(", ")
      ' 2>/dev/null || printf 'status=unknown')"
    else
      # Malformed response — track and bail loud after MAX_PARSE_FAILURES
      parse_failures=$(( parse_failures + 1 ))
      status_line="status=malformed_response (${parse_failures}/${MAX_PARSE_FAILURES})"
      if (( parse_failures >= MAX_PARSE_FAILURES )); then
        progress_done
        error "AOC backend returned malformed response ${MAX_PARSE_FAILURES} polls in a row."
        error "Last raw response (first 500 chars):"
        printf '%s\n' "${last_raw_response:0:500}" | sed 's/^/    /'
        error "Likely a 502/504 from the load balancer or an unhandled backend exception."
        error "Check AOC backend health: ${AOC_API}/health (if available)"
        return 1
      fi
    fi
    local elapsed=$(( $(date +%s) - started ))
    progress "${spinner[$spin_idx]} ${elapsed}s  ${status_line}"
    spin_idx=$(( (spin_idx + 1) % ${#spinner[@]} ))
    sleep "$interval"
  done
}

trigger_idempotent_publish() {
  local model_id="$1"
  step "Triggering idempotent in-graph modulation for ${model_id}"
  curl -sS -X POST "${AOC_API}/modulation/start" \
    "${AUTH_HEADER[@]}" \
    -H "Content-Type: application/json" \
    -d "{
      \"model_template_id\": \"${model_id}\",
      \"skip_modulation\": true,
      \"mode\": \"auto\",
      \"variant\": \"baseline\",
      \"kpi\": {\"targets\": [], \"maxSteps\": 1}
    }" >/dev/null
}

MOD_ENV_BACKUP=""
cleanup_mod_env() {
  if [[ -n "$MOD_ENV_BACKUP" && -f "$MOD_ENV_BACKUP" ]]; then
    mv "$MOD_ENV_BACKUP" "$LANG_DIR/.env"
  else
    rm -f "$LANG_DIR/.env"
  fi
}

prepare_modulator_env() {
  # Sweep stale backups left over from interrupted prior runs (Ctrl-C
  # while modulation was in flight skips the RETURN trap, leaving the
  # .bak.push.<PID> file behind with credentials in it). These were
  # also being rsynced to remote workers — defense-in-depth fix added
  # 2026-04-30: also exclude .env* in modulate_*_common.sh rsync.
  rm -f "$LANG_DIR"/.env.bak.push.* 2>/dev/null || true

  if [[ -f "$LANG_DIR/.env" ]]; then
    MOD_ENV_BACKUP="$LANG_DIR/.env.bak.push.$$"
    cp "$LANG_DIR/.env" "$MOD_ENV_BACKUP"
  fi
  cat >"$LANG_DIR/.env" <<EOF
BASE_URL=${AOC_API}
AOC_ORG_ID=${ORG_ID}
AOC_MODULATION_TOKEN=${API_TOKEN}
MODEL_TEMPLATE_ID=${MODEL_TEMPLATE_ID}
OUTDIR=./artifacts
HF_TOKEN=${HF_TOKEN}
MODULATOR_SDK_PACKAGE_SOURCE=${HELLOWORLD_SDK_PACKAGE_SOURCE:-${SDK_PACKAGE_SOURCE:-local}}
MODULATOR_SDK_VERSION=${HELLOWORLD_SDK_VERSION:-${SDK_VERSION:-}}
AOC_SEARCH_BUDGET=${AOC_SEARCH_BUDGET:-2}
AOC_STEPS_PER_TRIAL=${AOC_STEPS_PER_TRIAL:-10}
# Governance mode the worker should request from AOC. One of "standard"
# (default — both ECM variants searchable, no constraints), "indispensable"
# (backend coerces variant→multiplicative, ecm_init excludes random,
# ε∈[0.3,0.8]), or "idempotent" (skip-modulation publish). Default
# preserves backward-compatible behavior. Caller (e.g. run_experiment.sh)
# can override by exporting AOC_GOVERNANCE_MODE before invoking push.sh.
AOC_GOVERNANCE_MODE=${AOC_GOVERNANCE_MODE:-standard}
AOC_DATASET_PATH=${AOC_DATASET_PATH:-}
AOC_DATASET_NAME=${AOC_DATASET_NAME:-}
AOC_DATASET_CONFIG=${AOC_DATASET_CONFIG:-}
AOC_DATASET_SPLIT=${AOC_DATASET_SPLIT:-}
LAMBDA_API_KEY=${LAMBDA_API_KEY:-}
LAMBDA_SSH_KEY_NAME=${LAMBDA_SSH_KEY_NAME:-}
LAMBDA_SSH_KEY_PATH=${LAMBDA_SSH_KEY_PATH:-}
LAMBDA_INSTANCE_TYPES=${LAMBDA_INSTANCE_TYPES:-gpu_1x_a100,gpu_1x_a100_sxm4,gpu_1x_a10}
LAMBDA_API_BASE=${LAMBDA_API_BASE:-https://cloud.lambdalabs.com/api/v1}
EOF
}

run_modulation() {
  # RETURN handles normal completion. EXIT/INT/TERM handle Ctrl-C and
  # unexpected termination — without these, an interrupted run leaves a
  # .bak.push.<PID> file in the modulator dir with AOC credentials.
  trap cleanup_mod_env RETURN EXIT INT TERM
  prepare_modulator_env
  if [[ "$IDEMPOTENT" -eq 1 ]]; then
    trigger_idempotent_publish "$MODEL_TEMPLATE_ID"
  else
    case "$MODE" in
      local)
        info "Running language modulation locally..."
        (cd "$LANG_DIR" && ./modulate_local.sh)
        ;;
      lambda)
        # Lambda picks GPU type via LAMBDA_INSTANCE_TYPES env var, not a CLI
        # flag — the launcher tries each in order until one has capacity.
        info "Running language modulation on Lambda Cloud..."
        (cd "$LANG_DIR" && ./modulate_lambda.sh ${SKIP_BUILD_FLAG:+$SKIP_BUILD_FLAG} ${SKIP_PUSH_FLAG:+$SKIP_PUSH_FLAG})
        ;;
      gcp|*)
        info "Running language modulation on GCP (gpu=${GPU})..."
        (cd "$LANG_DIR" && ./modulate_gcp.sh "$GPU" ${SKIP_BUILD_FLAG:+$SKIP_BUILD_FLAG} ${SKIP_PUSH_FLAG:+$SKIP_PUSH_FLAG})
        ;;
    esac
  fi
  poll_until_ready "$MODEL_TEMPLATE_ID"
}

resolve_agent_template() {
  curl -sS "${AUTH_HEADER[@]}" "${AOC_API}/agents?type=TEMPLATE" | jq -r --arg lbl "$AGENT_LABEL" '
    map(select((.label // "") == $lbl))
    | first
    | (.id // .public_id // .ID // ._id // empty)'
}

create_agent_template() {
  local payload
  # `label` and `type` are reserved keywords in jq — used as object keys
  # they must be quoted as strings or jq errors with "unexpected label /
  # type". Same fix as fix/push-script-jq-cleanup; that branch never got
  # merged into A2A_demo.
  # Old unquoted form preserved for reference:
  #   { label: $label, description: $description, type: "TEMPLATE",
  #     models: [{ id: $model_id, config: { type: "language", policies: $policies } }] }
  payload=$(jq -n \
    --arg label_v "$AGENT_LABEL" \
    --arg description_v "$AGENT_DESCRIPTION" \
    --arg model_id "$MODEL_TEMPLATE_ID" \
    --argjson policies "$DEFAULT_POLICY_JSON" '
      {
        "label": $label_v,
        "description": $description_v,
        "type": "TEMPLATE",
        "models": [
          {
            "id": $model_id,
            "config": {
              "type": "language",
              "policies": $policies
            }
          }
        ]
      }')
  curl -sS -X POST "${AOC_API}/agents" \
    "${AUTH_HEADER[@]}" \
    -H "Content-Type: application/json" \
    -d "$payload"
}

if [[ "$FORCE_REGISTER" -eq 1 ]]; then
  MODEL_TEMPLATE_ID=""
else
  MODEL_TEMPLATE_ID="$(resolve_model_template || true)"
fi
print_plan
PHASE_START=$SECONDS

# ── Phase 1: Registration ────────────────────────────────────────
step "Resolving existing model template"
if [[ -z "$MODEL_TEMPLATE_ID" ]]; then
  CLI_TOKEN="$(cli_login)"
  register_model_template "$CLI_TOKEN"
  # AOC accepts the register POST synchronously but materializes the
  # template row in /models?type=TEMPLATE a few seconds later (HF fetch +
  # GCS upload), so a single-shot resolve right after register often
  # misses it. Poll until PUSH_RESOLVE_TIMEOUT_S elapses; override via
  # env var when staging is slow (default 300s = 5min).
  # MODEL_TEMPLATE_ID="$(resolve_model_template || true)"   # old single-shot
  RESOLVE_TIMEOUT_S="${PUSH_RESOLVE_TIMEOUT_S:-300}"
  RESOLVE_INTERVAL_S=2
  RESOLVE_MAX_ATTEMPTS=$(( RESOLVE_TIMEOUT_S / RESOLVE_INTERVAL_S ))
  step "Refreshing model template lookup after registration (timeout=${RESOLVE_TIMEOUT_S}s)"
  for attempt in $(seq 1 "$RESOLVE_MAX_ATTEMPTS"); do
    MODEL_TEMPLATE_ID="$(resolve_model_template || true)"
    if [[ -n "$MODEL_TEMPLATE_ID" ]]; then
      printf "\n"
      info "Template materialized after ${attempt} attempt(s) (~$(( attempt * RESOLVE_INTERVAL_S ))s)"
      break
    fi
    printf "."
    sleep "$RESOLVE_INTERVAL_S"
  done
  printf "\n"
  if [[ -n "$MODEL_TEMPLATE_ID" ]]; then
    wait_for_model_download "$MODEL_TEMPLATE_ID"
  fi
fi

if [[ -z "$MODEL_TEMPLATE_ID" ]]; then
  error "Failed to resolve language model template for ${MODEL_REPO}"
  # Diagnostic: show what AOC actually has so we can tell if it's still
  # async (template not there yet) vs a filter mismatch (template there
  # but resolve_model_template's jq filter rejected it).
  warn "Dumping last 5 templates from AOC for diagnosis:"
  fetch_model_templates \
    | jq -r '.items // [] | sort_by(.created_at // 0) | reverse | .[0:5]
              | .[] | "  - id=\(.ID // .public_id // ._id)  name=\(.name)  repo=\(.source_repo // "-")  kind=\(.model_kind // .kind // "-")  created=\(.created_at // "-")"' \
    2>/dev/null || warn "  (could not fetch /models?type=TEMPLATE)"
  printf "\n  ${BOLD}To retry with a longer timeout:${RESET}\n"
  printf "    PUSH_RESOLVE_TIMEOUT_S=600 ./quickstart.sh --a2a-demo\n\n"
  exit 1
fi

REGISTRATION_TIME=$(( SECONDS - PHASE_START ))
info "Resolved model template: ${DIM}${MODEL_TEMPLATE_ID}${RESET} ${DIM}(${REGISTRATION_TIME}s)${RESET}"
save_env_var MODEL_TEMPLATE_ID "$MODEL_TEMPLATE_ID"

# ── Phase 2: Modulation ──────────────────────────────────────────
PHASE_START=$SECONDS
if [[ "$FORCE_MODULATE" -eq 1 ]] || ! model_ready "$MODEL_TEMPLATE_ID"; then
  if [[ "$IDEMPOTENT" -eq 1 ]]; then
    step "Publishing model template (idempotent, skipping modulation)"
  else
    step "Publishing model template via full modulation path"
  fi
  run_modulation
  MODULATION_TIME=$(( SECONDS - PHASE_START ))
  info "Modulation complete ${DIM}(${MODULATION_TIME}s)${RESET}"
else
  info "Model template already modulated and ready; skipping modulation."
fi

# ── Phase 3: Agent template ───────────────────────────────────────
PHASE_START=$SECONDS
step "Resolving existing agent template"
AGENT_TEMPLATE_ID="$(resolve_agent_template || true)"
if [[ -z "$AGENT_TEMPLATE_ID" ]]; then
  step "Creating agent template: ${AGENT_LABEL}"
  RESP="$(create_agent_template)"
  AGENT_TEMPLATE_ID="$(echo "$RESP" | jq -r '.id // .public_id // .ID // ._id // .agent.id // .agent.public_id // empty')"
else
  warn "Agent template '${AGENT_LABEL}' already exists; reusing it."
fi

if [[ -z "$AGENT_TEMPLATE_ID" ]]; then
  error "Failed to create or resolve HelloWorld agent template"
  exit 1
fi

AGENT_TEMPLATE_TIME=$(( SECONDS - PHASE_START ))
save_env_var AGENT_TEMPLATE_ID "$AGENT_TEMPLATE_ID"

printf "\n"
printf "  ${GREEN}${BOLD}Bootstrap complete${RESET}\n"
printf "  ${DIM}────────────────────────────────────────${RESET}\n"
printf "  Model template   ${BOLD}${MODEL_TEMPLATE_ID}${RESET}\n"
printf "  Agent template   ${BOLD}${AGENT_TEMPLATE_ID}${RESET}\n"
printf "  ${DIM}Registration: ${REGISTRATION_TIME}s | Modulation: ${MODULATION_TIME:-0}s | Agent: ${AGENT_TEMPLATE_TIME}s${RESET}\n"
printf "\n"
